services:
  # Backend API service
  - type: web
    name: joachim-app-api
    env: node
    branch: example_1
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    disk:
      name: audio-storage
      mountPath: /opt/render/project/src/server/audio
      sizeGB: 1

  # Frontend static site
  - type: web
    name: joachim-app-frontend
    env: static
    branch: example_1
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://joachim-app-api.onrender.com 